attack: projected_gradient_descent
attack_mode: context
class_fraction: 0.000000001
epsilon: 0.0314
epsilon_step: 0.00094
norm: inf
num_iterations: 100
project_step: true
shot_fraction: 0.000000001
target_loss_mode: single_other_class
targeted: true
targeted_labels: shifted
use_true_target_labels: true
