attack: carlini_wagner
targeted: False
confidence: 0.0
c_lower: 1.0
c_upper: 1.0e+10
binary_search_steps: 15
max_iterations: 100
abort_early: False
optimizer_lr: 1.0e-2
init_rand: False
vary_success_criteria: False
success_fraction: 0.5
attack_mode: context
class_fraction: 1.0
shot_fraction: 0.1
