attack: elastic_net
confidence: 0.0
targeted: False
learning_rate: 1.0e-2
max_iterations: 500
binary_search_steps: 15
abort_early: True
beta: 1.0e-2
decision_rule: 'EN'
c_lower: 1.0e-3
c_upper: 1.0e+10
success_fraction: 0.5
attack_mode: context
class_fraction: 1.0
shot_fraction: 0.5
