attack: projected_gradient_descent
attack_mode: context
class_fraction: 1.0
epsilon: 0.0314
epsilon_step: 0.00094
norm: inf
num_iterations: 20
project_step: true
shot_fraction: 0.2
target_loss_mode: all
targeted: true
targeted_labels: shifted
use_true_target_labels: true
randomize: true